apiVersion: dbaas.postgres.ionoscloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    displayName: testDemo
    postgresVersion: "13"
    connections:
      - cidr:
        datacenterID:
        lanID:
    credentials:
      password:
      username:
    location:
    instances: 1
    cores: 2
    ram: 2048
    storageSize: 20480
    storageType: HDD
    synchronizationMode: ASYNCHRONOUS
  providerConfigRef:
    name: example
