apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  forProvider:
    name: exampleDatacenter
    location: de/txl
    description: test
  providerConfigRef:
    name: example
---
apiVersion: dbaas.postgres.ionoscloud.crossplane.io/v1alpha1
kind: Cluster
metadata:
  name: example
spec:
  forProvider:
    displayName: testDemo
    postgresVersion: "13"
    connections:
      - datacenterConfig:
          datacenterIdRef:
            name: example
        lanId: "1"
        cidr: 192.168.1.100/24
    credentials:
      username: test
      password: test12345
    location: de/txl
    instances: 1
    cores: 2
    ram: 2048
    storageSize: 20480
    storageType: HDD
    synchronizationMode: ASYNCHRONOUS
  providerConfigRef:
    name: example
