apiVersion: v2
name: root-app
description: "Umbrella chart for the Ionoscloud Crossplane Provider"
version: 1.0.0
dependencies:
  - name: crossplane
    version: 1.15.2
    repository: https://charts.crossplane.io/stable