apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: FirewallRule
metadata:
  name: examplefr
spec:
  forProvider:
    name: exampleFirewallRule
    protocol: ANY
    type: INGRESS
    datacenterConfig:
      datacenterIdRef:
        name: example
    serverConfig:
      serverIdRef:
        name: exampleserver
    nicConfig:
      nicIdRef:
        name: examplenic
  providerConfigRef:
    name: example
