apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  name: examplevolume
spec:
  forProvider:
    name: exampleVolume
    size: 30
    type: HDD
    bus: VIRTIO
    licenceType: LINUX
    availabilityZone: AUTO
#    imageAlias: ubuntu:latest
#    imagePassword:
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
