apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-ag
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ionos-cloud/crossplane-provider-ionoscloud.git
    path: charts/crossplane-ag
    targetRevision: feat/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    # When empty, just sets resource tracking on the created namespace
    managedNamespaceMetadata:
      labels:
      annotations:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
