apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane-resources
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ionos-cloud/crossplane-provider-ionoscloud.git
    path: examples/argo-cd
    targetRevision: feat/argocd
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
