# Use this file to create a K8s Dataplatform CR.
# Required values for creating a Dataplatform NodePool CR are:
# - Name,
# - ClusterConfig (via ID or reference),
# - DatacenterConfig (via ID or reference),
# - Name,
# - NodeCount
apiVersion: dataplatform.ionoscloud.crossplane.io/v1alpha1
kind: DataplatformNodepool
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleDataplatformNodepool
    nodeCount: 2
    # Note: If the CPU Family is not set, the Crossplane Provider
    # will set the first one offered by the Datacenter.
#    cpuFamily: INTEL_XEON
#    coresCount: 1
#    ramSize: 2048
#    availabilityZone: AUTO
#    storageType: HDD
#    storageSize: 10
    datacenterConfig:
      datacenterIdRef:
        name: example
    clusterConfig:
      ClusterIdRef:
        name: example
    storageType: HDD
  providerConfigRef:
    name: example
