# Use this file to create Datacenter, and Dataplatform Cluster CRs.
# Required values for creating a Datacenter CR are:
# - Location.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleDatacenter
    location: de/txl
    description: test
  providerConfigRef:
    name: example
---
# Required values for creating a Dataplatform luster CR are:
# - Datacenter ID or Reference
# - Name
# - Version
apiVersion: dataplatform.ionoscloud.crossplane.io/v1alpha1
kind: DataplatformCluster
metadata:
  name: example4
managementPolicies:
  - "*"
spec:
  forProvider:
    datacenterConfig:
      datacenterIdRef:
        name: example
    name: exampleCluster
    version: "23.11"
  providerConfigRef:
    name: example
