# Use this file to create a Datacenter CR, a Volume CR,
# a Server CR, a Lan CR, a Nic CR, a FirewallRule CR
# and an IPFailover CR.
# ! Before applying this file, make sure to add reserved
# ips to the Nic CR and to the IPFailover CR.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  forProvider:
    name: exampleDatacenter
    location: us/las
    description: test
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  name: examplevolume
spec:
  forProvider:
    name: exampleVolume
    size: 30
    type: HDD
    bus: VIRTIO
    licenceType: LINUX
    availabilityZone: AUTO
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Server
metadata:
  name: exampleserver
spec:
  forProvider:
    name: exampleServer
    cores: 2
    ram: 2048
    availabilityZone: AUTO
    cpuFamily: AMD_OPTERON
    datacenterConfig:
      datacenterIdRef:
        name: example
    volumeConfig:
      volumeIdRef:
        name: examplevolume
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
spec:
  forProvider:
    name: exampleLan
    public: true
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Nic
metadata:
  name: examplenic
spec:
  forProvider:
    name: exampleNic
    dhcp: false
    ips:
      -
    datacenterConfig:
      datacenterIdRef:
        name: example
    serverConfig:
      serverIdRef:
        name: exampleserver
    lanConfig:
      lanIdRef:
        name: examplelan
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: FirewallRule
metadata:
  name: examplefr
spec:
  forProvider:
    name: exampleFirewallRule
    protocol: ANY
    type: INGRESS
    datacenterConfig:
      datacenterIdRef:
        name: example
    serverConfig:
      serverIdRef:
        name: exampleserver
    nicConfig:
      nicIdRef:
        name: examplenic
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: IPFailover
metadata:
  name: exampleipfailover
spec:
  forProvider:
    ip:
    datacenterConfig:
      datacenterIdRef:
        name: example
    lanConfig:
      lanIdRef:
        name: examplelan
    nicConfig:
      nicIdRef:
        name: examplenic
  providerConfigRef:
    name: example
