# Use this file to create a IPBlock CR, a Datacenter CR,
# a Volume CR, a Server CR, a Lan CR, a Nic CR,
# a FirewallRule CR and an IPFailover CR.
# ! Before applying this file, make sure to check values set.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: IPBlock
metadata:
  name: exampleipblock
spec:
  .managementPolicies:
    - "*"
  forProvider:
    name: exampleIpBlock
    size: 2
    location: us/las
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleDatacenter
    location: us/las
    description: test
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  name: examplevolume
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleVolume
    size: 30
    type: HDD
    bus: VIRTIO
    licenceType: LINUX
    availabilityZone: AUTO
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Server
metadata:
  name: exampleserver
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleServer
    cores: 2
    ram: 2048
    availabilityZone: AUTO
    cpuFamily: AMD_OPTERON
    datacenterConfig:
      datacenterIdRef:
        name: example
    volumeConfig:
      volumeIdRef:
        name: examplevolume
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleLan
    public: true
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Nic
metadata:
  name: examplenic
spec:
  forProvider:
    name: exampleNic
    dhcp: false
    ipsConfigs:
      ipsBlockConfigs:
        - ipBlockIdRef:
            name: exampleipblock
    datacenterConfig:
      datacenterIdRef:
        name: example
    serverConfig:
      serverIdRef:
        name: exampleserver
    lanConfig:
      lanIdRef:
        name: examplelan
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: FirewallRule
metadata:
  name: examplefr
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleFirewallRule
    protocol: ANY
    type: INGRESS
    sourceIpConfig:
      ipBlockConfig:
        ipBlockIdRef:
          name: exampleipblock
        index: 0
    targetIpConfig:
      ipBlockConfig:
        ipBlockIdRef:
          name: exampleipblock
        index: 1
    datacenterConfig:
      datacenterIdRef:
        name: example
    serverConfig:
      serverIdRef:
        name: exampleserver
    nicConfig:
      nicIdRef:
        name: examplenic
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: IPFailover
metadata:
  name: exampleipfailover
spec:
  managementPolicies:
    - "*"
  forProvider:
    ipConfig:
      ipBlockConfig:
        ipBlockIdRef:
          name: exampleipblock
        index: 0
    datacenterConfig:
      datacenterIdRef:
        name: example
    lanConfig:
      lanIdRef:
        name: examplelan
    nicConfig:
      nicIdRef:
        name: examplenic
  providerConfigRef:
    name: example
