apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: CubeServer
metadata:
  name: examplecubeserver
spec:
  forProvider:
    name: exampleCubeServer
    template:
      name: CUBES XS
    availabilityZone: AUTO
    cpuFamily: AMD_OPTERON
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
