# Use this file to create a Cube Server CR.
# Required values for creating a Cube Server CR are:
# - DatacenterConfig (via ID or reference),
# - Template Name or ID,
# - Volume.
# Note: Make sure the datacenter's location (e.g. de/txl)
# supports servers of type CUBE!
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: CubeServer
metadata:
  name: examplecubeserver
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleCubeServer
    availabilityZone: AUTO
    template:
      name: CUBES XS
    volume:
      name: exampleDasVolume
      bus: VIRTIO
      licenceType: LINUX
    #      imageAlias:
    #      imagePassword:
    #      image:
    #      userData: # MUST BE ENCODED IN BASE64!
    #      backupUnitConfig:
    #        backupUnitIdRef:
    #          name:
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
