# Use this file to create a Datacenter CR.
# Required values for creating a Datacenter CR are:
# - Location.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleDatacenter4
    location: us/las
    description: test
#    secAuthProtection: true
  providerConfigRef:
    name: example
