apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: exampledc
spec:
  forProvider:
    name: test
    location: us/las
    description: test
  providerConfigRef:
    name: example

