apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: IPFailover
metadata:
  name: exampleipfailovers
spec:
  forProvider:
    ip: 162.222.200.7
    datacenterConfig:
      datacenterIdRef:
        name: example
    lanConfig:
      lanIdRef:
        name: examplelan
    nicConfig:
      nicIdRef:
        name: examplenic
  providerConfigRef:
    name: example
