# Use this file to create a Lan CR.
# Required values for creating a Lan CR are:
# - DatacenterConfig (via ID or reference),
# - Public.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleLan
    #pcc:
    #  PrivateCrossConnectIdRef:
    #    name: examplePcc
    public: true
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
