# Use this file to create a Management Group CR.
# Required values for creating a Management Group CR:
# - Name,
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: ManagementGroup
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleGroup
    createDataCenter: true
    reserveIp: true
    userConfig:
      - userIdRef:
          name: xplane-test-user
  providerConfigRef:
    name: example
