# Use this file to create a Nic CR.
# Required values for creating a Nic CR are:
# - DatacenterConfig (via ID or reference),
# - ServerConfig (via ID or reference),
# - LanConfig (via ID or reference),
# - DHCP.
# IPs can be set directly or via ipBlocks references and indexes.
# If both ips and ipBlockConfigs fields are set, only the ips
# field will be used.
# If no ips are set, API will automatically set one.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Nic
metadata:
  name: examplenic
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleNic
    dhcp: false
    ipsConfigs:
      ipsBlockConfigs:
        - ipBlockIdRef:
            name: example
          indexes: [ 1 ]
        - ipBlockIdRef:
            name: example
    #    firewallActive: true
    firewallType: INGRESS
    datacenterConfig:
      datacenterIdRef:
        name: example
    serverConfig:
      serverIdRef:
        name: exampleserver
    lanConfig:
      lanIdRef:
        name: examplelan
  providerConfigRef:
    name: example
