# Use this file to create a S3 key.
# Required values for creating a S3Key CR are:
# userId (via ID).
# s3SecretKey is automatically returned by the API and will be saved in s3key secret in crossplane-system namespace.
# To see the data inside the secret, run the following commands:
# kubectl get secrets/s3key --template={{.data.s3SecretKey}} | base64
# kubectl get secrets/s3key --template={{.data.s3KeyID}} | base64
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: S3Key
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
#    replace with the user id for which you want the s3 key to be created
    userID: "f33b1393-1f62-4358-8df9-2f7228b9370f"
#    optional, can be left out. the key can only be updated to false after creation
    active: true
  providerConfigRef:
    name: example
  publishConnectionDetailsTo:
    name: my-s3-key
    metadata:
      labels:
        environment: prod-s3-bucket
      annotations:
        test.annotation.io/secret-type: key
        another.test.annotation.io/secret-scope: object-storage
    configRef:
      name: default