# Use this file to create a Volume CR.
# Required values for creating a Volume CR are:
# - DatacenterConfig (via ID or reference),
# - Size,
# - Type,
# - Licence Type, Image ID or Image Alias.
# Note: when using images, it is recommended to use SSH Keys or Image Password.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleDatacenter
    location: us/las
    description: test
  #    secAuthProtection: true
  providerConfigRef:
    name: example
---
# Use this file to create a Lan CR.
# Required values for creating a Lan CR are:
# - DatacenterConfig (via ID or reference),
# - Public.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleLan
    public: false
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: ServerSet
metadata:
  name: serverset
spec:
  managementPolicies:
    - "*"
  providerConfigRef:
    name: example
  forProvider:
    replicas: 1
    datacenterConfig:
      datacenterIdRef:
        name: example
    template:
      metadata:
        name: server-sample
        labels:
          key: value
      spec:
        cpuFamily: INTEL_XEON
        cores: 1
        ram: 1024
        nics:
          - name: nic-sample
            ipv4: "10.0.0.1/24"
            reference: examplelan
    bootVolumeTemplate:
      spec:
        updateStrategy:
#          createBeforeDestroyBootVolume createAllBeforeDestroy
          type: "createBeforeDestroyBootVolume"
        image: "28d0fa34-927f-11ee-8008-6202af74e858"
        size: 10
        type: HDD
#        todo - add sshKeys or imagePassword
#        todo - add userdata in volume creation
        userData: "" #cloud-config
