apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Server
metadata:
  name: exampleserver
spec:
  forProvider:
    name: test
    cores: 4
    ram: 2048
    datacenterIDRef:
      name: exampledc
    availabilityZone: AUTO
    cpuFamily: AMD_OPTERON
  providerConfigRef:
    name: example
