# Use this file to create a Volume CR.
# Required values for creating a Volume CR are:
# - DatacenterConfig (via ID or reference),
# - Size,
# - Type,
# - Licence Type, Image ID or Image Alias.
# Note: when using images, it is recommended to use SSH Keys or Image Password.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleDatacenter
    location: de/fra/2
    description: test
  #    secAuthProtection: true
  providerConfigRef:
    name: example
---
# Use this file to create a Lan CR.
# Required values for creating a Lan CR are:
# - DatacenterConfig (via ID or reference),
# - Public.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleLan
    public: false
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan2
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleLan2
    public: false
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: ServerSet
metadata:
  name: serverset
spec:
  managementPolicies:
    - "*"
  providerConfigRef:
    name: example
  forProvider:
    replicas: 2
    datacenterConfig:
      datacenterIdRef:
        name: example
    template:
      metadata:
        name: server-sample
        labels:
          key: value
      spec:
        cores: 1
        ram: 1024
        nics:
          - name: nic-sample
            dhcp: false
#            needs to be created before serverset. Serverset will not wait until it is populated
            lanReference: examplelan
          - name: nic-sample2
            dhcp: false
            dhcpv6: true
            lanReference: examplelan2
    identityConfigMap:
      name: "config-lease"
      namespace: "default"
      keyName: "identity"
    bootVolumeTemplate:
      metadata:
        name: volumeboot
      spec:
        updateStrategy:
#          createBeforeDestroyBootVolume createAllBeforeDestroy
          type: "createBeforeDestroyBootVolume"
        image: "40b08619-2b4a-11f0-ae1e-52b0f2b9ddd5"
        size: 20
        type: HDD
        userData: "" #cloud-config
        imagePassword: "thisshouldbesecret"
        substitutions:
          - options:
              cidr: "fd1d:15db:cf64:1337::/64"
            key: __ipv6Address
            type: ipv6Address
            unique: true
          - options:
              cidr: "192.168.42.0/24"
            key: ipv4Address
            type: ipv4Address
            unique: true
---
# the active server name is stored as a value for the identity key.
# the name, namespace and key name must match what is configured in the identityConfigMap
# of the serverset
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-lease
  namespace: default
data:
  identity: "server-sample-1-0"