apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  forProvider:
    name: exampleDatacenter
    location: us/las
    description: test
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  name: examplevolume
spec:
  forProvider:
    name: exampleVolume
    size: 30
    type: HDD
    bus: VIRTIO
    licenceType: LINUX
    availabilityZone: AUTO
    #    imageAlias: ubuntu:latest
    #    imagePassword:
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Server
metadata:
  name: exampleserver
spec:
  forProvider:
    name: exampleServer
    cores: 4
    ram: 2048
    availabilityZone: AUTO
    cpuFamily: AMD_OPTERON
    datacenterConfig:
      datacenterIdRef:
        name: example
    volumeConfig:
      volumeIdRef:
        name: examplevolume
  providerConfigRef:
    name: example
