# Use this file to create a Volume CR.
# Required values for creating a Volume CR are:
# - DatacenterConfig (via ID or reference),
# - Size,
# - Type,
# - Licence Type, Image ID or Image Alias.
# Note: when using images, it is recommended to use SSH Keys or Image Password.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Volume
metadata:
  name: examplevolume
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleVolume
    size: 30
    type: HDD
    bus: VIRTIO
    licenceType: LINUX
    availabilityZone: AUTO
    substitutions:
      - key: $NIC0_ipv6Address
        type: random-ipv6
        unique: true
        additionalProperties:
          cidr: fd00:1337:1::/64
    #    imageAlias: ubuntu:latest
    #    imagePassword:
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
