# Use this file to create Datacenter, Lan and DBaaS mongo Cluster CRs.
# Required values for creating a Datacenter CR are:
# - Location.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleDatacenter
    location: de/txl
    description: test
  providerConfigRef:
    name: example
---
# Required values for creating a Lan CR are:
# - DatacenterConfig (via ID or reference),
# - Public.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
managementPolicies:
  - "*"
spec:
  forProvider:
    name: exampleLan
    public: false
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
# Required values for creating a DBaaS Mongo Cluster CR are:
# - MongoDBVersion,
# - Instances,
# - Connection (Datacenter ID or Reference, Lan ID and CIDR),
# - Location (in sync with Datacenter),
# - DisplayName,
# - Credentials,
# - Synchronization Mode.
apiVersion: dbaas.mongo.ionoscloud.crossplane.io/v1alpha1
kind: MongoCluster
metadata:
  name: example
managementPolicies:
  - "*"
spec:
  forProvider:
    displayName: testDemo
    mongoDBVersion: "5.0"
    connections:
      - datacenterConfig:
          datacenterIdRef:
            name: example
        lanConfig:
          lanIdRef:
            name: examplelan
        cidr:
          - 192.168.1.100/24
    location: de/txl
    instances: 1
    type   : "sharded-cluster"
    shards: 2
    edition: "enterprise"
    ram    : 2048
    cores  : 1
    storageSize: 5120
    storageType: "HDD"
#    templateID: 6b78ea06-ee0e-4689-998c-fc9c46e781f6
    synchronizationMode: ASYNCHRONOUS
  providerConfigRef:
    name: example
