apiVersion: dbaas.ionoscloud.crossplane.io/v1alpha1
kind: PostgresUser
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    credentials:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: psqlcreds
        key: credentials
    clusterConfig:
      ClusterIdRef:
        name: example
  providerConfigRef:
    name: example
