apiVersion: v1
kind: Secret
metadata:
  name: psqlcreds
  namespace: crossplane-system
data:
  credentials: eyJ1c2VybmFtZSI6InRlc3R1c2VyMiIsInBhc3N3b3JkIjoidGVzdHBhc3N3b3JkIn0=
---
# Use this file to create Datacenter, Lan and DBaaS Postgres Cluster CRs.
# Required values for creating a Datacenter CR are:
# - Location.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Datacenter
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: postgresDatacenter
    location: de/txl
    description: test
  providerConfigRef:
    name: example
---
# Required values for creating a Lan CR are:
# - DatacenterConfig (via ID or reference),
# - Public.
apiVersion: compute.ionoscloud.crossplane.io/v1alpha1
kind: Lan
metadata:
  name: examplelan
spec:
  managementPolicies:
    - "*"
  forProvider:
    name: exampleLan
    public: false
    datacenterConfig:
      datacenterIdRef:
        name: example
  providerConfigRef:
    name: example
---
# Required values for creating a DBaaS Postgres Cluster CR are:
# - PostgresVersion,
# - Instances,
# - Cores,
# - RAM,
# - Storage Size,
# - Storage Type,
# - Connection (Datacenter ID or Reference, Lan ID and CIDR),
# - Location (in sync with Datacenter),
# - DisplayName,
# - Credentials,
# - Synchronization Mode.
apiVersion: dbaas.ionoscloud.crossplane.io/v1alpha1
kind: PostgresCluster
metadata:
  name: example
spec:
  managementPolicies:
    - "*"
  forProvider:
    displayName: testDemo
    postgresVersion: "13"
    connections:
      - datacenterConfig:
          datacenterIdRef:
            name: example
        lanConfig:
          lanIdRef:
            name: examplelan
        cidr: 192.168.1.100/24
    credentials:
      source: Secret
      secretRef:
        namespace: crossplane-system
        name: psqlcreds
        key: credentials
    location: es/vit
    instances: 1
    cores: 2
    ram: 2048
    storageSize: 20480
    storageType: HDD
    synchronizationMode: ASYNCHRONOUS
  providerConfigRef:
    name: example
