apiVersion: platform.example.org/v1alpha1
kind: XClusterInstance
metadata:
  name: my-cluster-refxr
spec:
  parameters:
    datacenterName: testExampleXR
    datacenterDescription: testExampleDescriptionXR
    datacenterLocation: us/las
    clusterName: testK8sClusterXR
    clusterPublic: true
    nodepoolName: testK8sNodepoolXR
    nodepoolCpuFamily: INTEL_XEON
