/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/pkg/reference"
	v1alpha1 "github.com/ionos-cloud/crossplane-provider-ionoscloud/apis/compute/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this FlowLog.
func (mg *FlowLog) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.DatacenterCfg.DatacenterID,
		Extract:      v1alpha1.ExtractDatacenterID(),
		Reference:    mg.Spec.ForProvider.DatacenterCfg.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterCfg.DatacenterIDSelector,
		To: reference.To{
			List:    &v1alpha1.DatacenterList{},
			Managed: &v1alpha1.Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterCfg.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterCfg.DatacenterID = rsp.ResolvedValue
	mg.Spec.ForProvider.DatacenterCfg.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerID,
		Extract:      ExtractNetworkLoadBalancerID(),
		Reference:    mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerIDRef,
		Selector:     mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerIDSelector,
		To: reference.To{
			List:    &NetworkLoadBalancerList{},
			Managed: &NetworkLoadBalancer{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerID")
	}
	mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerID = rsp.ResolvedValue
	mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ForwardingRule.
func (mg *ForwardingRule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.DatacenterCfg.DatacenterID,
		Extract:      v1alpha1.ExtractDatacenterID(),
		Reference:    mg.Spec.ForProvider.DatacenterCfg.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterCfg.DatacenterIDSelector,
		To: reference.To{
			List:    &v1alpha1.DatacenterList{},
			Managed: &v1alpha1.Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterCfg.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterCfg.DatacenterID = rsp.ResolvedValue
	mg.Spec.ForProvider.DatacenterCfg.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerID,
		Extract:      ExtractNetworkLoadBalancerID(),
		Reference:    mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerIDRef,
		Selector:     mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerIDSelector,
		To: reference.To{
			List:    &NetworkLoadBalancerList{},
			Managed: &NetworkLoadBalancer{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerID")
	}
	mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerID = rsp.ResolvedValue
	mg.Spec.ForProvider.NLBCfg.NetworkLoadBalancerIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ListenerIP.IPBlockConfig.IPBlockID,
		Extract:      v1alpha1.ExtractIPBlockID(),
		Reference:    mg.Spec.ForProvider.ListenerIP.IPBlockConfig.IPBlockIDRef,
		Selector:     mg.Spec.ForProvider.ListenerIP.IPBlockConfig.IPBlockIDSelector,
		To: reference.To{
			List:    &v1alpha1.IPBlockList{},
			Managed: &v1alpha1.IPBlock{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ListenerIP.IPBlockConfig.IPBlockID")
	}
	mg.Spec.ForProvider.ListenerIP.IPBlockConfig.IPBlockID = rsp.ResolvedValue
	mg.Spec.ForProvider.ListenerIP.IPBlockConfig.IPBlockIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Targets); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.Targets[i3].IP.IPBlockConfig.IPBlockID,
			Extract:      v1alpha1.ExtractIPBlockID(),
			Reference:    mg.Spec.ForProvider.Targets[i3].IP.IPBlockConfig.IPBlockIDRef,
			Selector:     mg.Spec.ForProvider.Targets[i3].IP.IPBlockConfig.IPBlockIDSelector,
			To: reference.To{
				List:    &v1alpha1.IPBlockList{},
				Managed: &v1alpha1.IPBlock{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Targets[i3].IP.IPBlockConfig.IPBlockID")
		}
		mg.Spec.ForProvider.Targets[i3].IP.IPBlockConfig.IPBlockID = rsp.ResolvedValue
		mg.Spec.ForProvider.Targets[i3].IP.IPBlockConfig.IPBlockIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this NetworkLoadBalancer.
func (mg *NetworkLoadBalancer) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.DatacenterCfg.DatacenterID,
		Extract:      v1alpha1.ExtractDatacenterID(),
		Reference:    mg.Spec.ForProvider.DatacenterCfg.DatacenterIDRef,
		Selector:     mg.Spec.ForProvider.DatacenterCfg.DatacenterIDSelector,
		To: reference.To{
			List:    &v1alpha1.DatacenterList{},
			Managed: &v1alpha1.Datacenter{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DatacenterCfg.DatacenterID")
	}
	mg.Spec.ForProvider.DatacenterCfg.DatacenterID = rsp.ResolvedValue
	mg.Spec.ForProvider.DatacenterCfg.DatacenterIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.ListenerLanCfg.LanID,
		Extract:      v1alpha1.ExtractLanID(),
		Reference:    mg.Spec.ForProvider.ListenerLanCfg.LanIDRef,
		Selector:     mg.Spec.ForProvider.ListenerLanCfg.LanIDSelector,
		To: reference.To{
			List:    &v1alpha1.LanList{},
			Managed: &v1alpha1.Lan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ListenerLanCfg.LanID")
	}
	mg.Spec.ForProvider.ListenerLanCfg.LanID = rsp.ResolvedValue
	mg.Spec.ForProvider.ListenerLanCfg.LanIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: mg.Spec.ForProvider.TargetLanCfg.LanID,
		Extract:      v1alpha1.ExtractLanID(),
		Reference:    mg.Spec.ForProvider.TargetLanCfg.LanIDRef,
		Selector:     mg.Spec.ForProvider.TargetLanCfg.LanIDSelector,
		To: reference.To{
			List:    &v1alpha1.LanList{},
			Managed: &v1alpha1.Lan{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TargetLanCfg.LanID")
	}
	mg.Spec.ForProvider.TargetLanCfg.LanID = rsp.ResolvedValue
	mg.Spec.ForProvider.TargetLanCfg.LanIDRef = rsp.ResolvedReference

	for i4 := 0; i4 < len(mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg); i4++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg[i4].IPBlock.IPBlockID,
			Extract:      v1alpha1.ExtractIPBlockID(),
			Reference:    mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg[i4].IPBlock.IPBlockIDRef,
			Selector:     mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg[i4].IPBlock.IPBlockIDSelector,
			To: reference.To{
				List:    &v1alpha1.IPBlockList{},
				Managed: &v1alpha1.IPBlock{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg[i4].IPBlock.IPBlockID")
		}
		mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg[i4].IPBlock.IPBlockID = rsp.ResolvedValue
		mg.Spec.ForProvider.IpsCfg.IPsBlocksCfg[i4].IPBlock.IPBlockIDRef = rsp.ResolvedReference

	}

	return nil
}
