apiVersion: alb.ionoscloud.crossplane.io/v1alpha1
kind: ApplicationLoadBalancer
metadata:
  name: example
spec:
  forProvider:
    datacenterConfig:
      datacenterIdRef:
        name: example
    name: exampleApplicationLoadBalancer
    targetLanConfig:
      lanIdRef:
        name: example
    listenerLanConfig:
      lanIdRef:
        name: examplelan
    ipsConfig:
      ipsBlockConfigs:
        - ipBlockIdRef:
            name: example
          indexes: [ 0 ]
  providerConfigRef:
    name: example
