apiVersion: v2
name: argo-cd
description: "Wrapper chart for installing argo-cd"
version: 1.0.0
dependencies:
  - name: argo-cd
    version: 6.7.13
    repository: https://argoproj.github.io/argo-helm