argo-cd:
  dex:
    enabled: false
  notifications:
    enabled: false
  applicationSet:
    enabled: false
  server:
    extraArgs:
      - --insecure

# -- Repositories list to be used by applications
## Creates a secret for each key/value specified below to create repositories
## Note: the last example in the list would use a repository credential template, configured under "configs.credentialTemplates".
#repositories: {}
  # istio-helm-repo:
  #   url: https://storage.googleapis.com/istio-prerelease/daily-build/master-latest-daily/charts
  #   name: istio.io
  #   type: helm
  # private-helm-repo:
  #   url: https://my-private-chart-repo.internal
  #   name: private-repo
  #   type: helm
  #   password: my-password
  #   username: my-username
  # private-repo:
#   url: https://github.com/argoproj/private-repo
