apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: debug-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      strategy: {}
      template:
        spec:
          containers:
          - args:
            - --debug
            # In order to enable name uniqueness support for IONOS Cloud Resources, uncomment the next line:
            # - --unique-names
            name: package-runtime
            resources: {}