apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
    # In order to enable name uniqueness support for IONOS Cloud Resources, uncomment the next line:
    # - --unique-names
