apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-ionos
spec:
  package: ghcr.io/ionos-cloud/crossplane-provider-ionoscloud:latest
  # Uncomment the following lines in order to see logs
  # for Crossplane Provider IONOS Cloud controller pod:
  # controllerConfigRef:
  #  name: debug-config
