// Code generated by MockGen. DO NOT EDIT.
// Source: ../../clients/compute/user/user.go
//
// Generated by this command:
//
//	mockgen -source=../../clients/compute/user/user.go -destination=compute/user/user.go -package user
//

// Package user is a generated GoMock package.
package user

import (
	"context"
	"reflect"

	ionoscloud "github.com/ionos-cloud/sdk-go/v6"
	"go.uber.org/mock/gomock"

	"github.com/ionos-cloud/crossplane-provider-ionoscloud/apis/compute/v1alpha1"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// AddUserToGroup mocks base method.
func (m *MockClient) AddUserToGroup(ctx context.Context, groupID, userID string) (ionoscloud.User, *ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserToGroup", ctx, groupID, userID)
	ret0, _ := ret[0].(ionoscloud.User)
	ret1, _ := ret[1].(*ionoscloud.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// AddUserToGroup indicates an expected call of AddUserToGroup.
func (mr *MockClientMockRecorder) AddUserToGroup(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserToGroup", reflect.TypeOf((*MockClient)(nil).AddUserToGroup), ctx, groupID, userID)
}

// CreateUser mocks base method.
func (m *MockClient) CreateUser(ctx context.Context, p v1alpha1.UserParameters, passw string) (ionoscloud.User, *ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, p, passw)
	ret0, _ := ret[0].(ionoscloud.User)
	ret1, _ := ret[1].(*ionoscloud.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockClientMockRecorder) CreateUser(ctx, p, passw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockClient)(nil).CreateUser), ctx, p, passw)
}

// DeleteUser mocks base method.
func (m *MockClient) DeleteUser(ctx context.Context, id string) (*ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", ctx, id)
	ret0, _ := ret[0].(*ionoscloud.APIResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockClientMockRecorder) DeleteUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockClient)(nil).DeleteUser), ctx, id)
}

// DeleteUserFromGroup mocks base method.
func (m *MockClient) DeleteUserFromGroup(ctx context.Context, groupID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUserFromGroup", ctx, groupID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUserFromGroup indicates an expected call of DeleteUserFromGroup.
func (mr *MockClientMockRecorder) DeleteUserFromGroup(ctx, groupID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUserFromGroup", reflect.TypeOf((*MockClient)(nil).DeleteUserFromGroup), ctx, groupID, userID)
}

// GetAPIClient mocks base method.
func (m *MockClient) GetAPIClient() *ionoscloud.APIClient {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAPIClient")
	ret0, _ := ret[0].(*ionoscloud.APIClient)
	return ret0
}

// GetAPIClient indicates an expected call of GetAPIClient.
func (mr *MockClientMockRecorder) GetAPIClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAPIClient", reflect.TypeOf((*MockClient)(nil).GetAPIClient))
}

// GetUser mocks base method.
func (m *MockClient) GetUser(ctx context.Context, id string) (ionoscloud.User, *ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", ctx, id)
	ret0, _ := ret[0].(ionoscloud.User)
	ret1, _ := ret[1].(*ionoscloud.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetUser indicates an expected call of GetUser.
func (mr *MockClientMockRecorder) GetUser(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockClient)(nil).GetUser), ctx, id)
}

// GetUserGroups mocks base method.
func (m *MockClient) GetUserGroups(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserGroups", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserGroups indicates an expected call of GetUserGroups.
func (mr *MockClientMockRecorder) GetUserGroups(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserGroups", reflect.TypeOf((*MockClient)(nil).GetUserGroups), ctx, userID)
}

// UpdateUser mocks base method.
func (m *MockClient) UpdateUser(ctx context.Context, id string, p v1alpha1.UserParameters, passw string) (ionoscloud.User, *ionoscloud.APIResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", ctx, id, p, passw)
	ret0, _ := ret[0].(ionoscloud.User)
	ret1, _ := ret[1].(*ionoscloud.APIResponse)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockClientMockRecorder) UpdateUser(ctx, id, p, passw any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockClient)(nil).UpdateUser), ctx, id, p, passw)
}

// UpdateUserGroups mocks base method.
func (m *MockClient) UpdateUserGroups(ctx context.Context, userID string, observedGroupIDs []string, configuredGroupIDs *[]string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserGroups", ctx, userID, observedGroupIDs, configuredGroupIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserGroups indicates an expected call of UpdateUserGroups.
func (mr *MockClientMockRecorder) UpdateUserGroups(ctx, userID, observedGroupIDs, configuredGroupIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserGroups", reflect.TypeOf((*MockClient)(nil).UpdateUserGroups), ctx, userID, observedGroupIDs, configuredGroupIDs)
}
