apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdatacenters.compute.example.org
spec:
  group: compute.example.org
  names:
    kind: XDatacenter
    listKind: XDatacenterList
    plural: xdatacenters
    singular: xdatacenter
  claimNames:
    kind: Datacenter
    plural: datacenter
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          description: A XDatacenter is a composite resource
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    name:
                      type: string
                    description:
                      type: string
                    location:
                      type: string
                  required:
                    - location
              required:
                - parameters
