package k8s

// States of K8s Resources
const (
	AVAILABLE  = "AVAILABLE"
	BUSY       = "BUSY"
	DEPLOYING  = "DEPLOYING"
	ACTIVE     = "ACTIVE"
	INACTIVE   = "INACTIVE"
	UPDATING   = "UPDATING"
	DESTROYING = "DESTROYING"
	FAILED     = "FAILED"
	TERMINATED = "TERMINATED"
	SUSPENDED  = "SUSPENDED"
)
